### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by Mokerstier** [sjagoori/progressive-web-apps-2021#3]
https://github.com/sjagoori/progressive-web-apps-2021/blob/58f164ab36f7b4d40c054bf134c5d4e1c6030d9a/routes/router.js#L14-L36

Volgens mij hoort dit niet in je routes te staan maar in je API module?

**Comment by sjagoori** [comment]
Ja en nee, ik moet nog helemaal opnieuw indelen zodat ik de data mee kan nemen bij de build. Dan hoef ik ook 1 extra api call te maken voor de build! Zal wss iets van caching worden
